name: display
description: Represents a device's screen or other container such as an iframe.
version: 0.0.1
author: Jacob Phillips <jifalops@gmail.com>
homepage: https://github.com/jifalops/display

dependencies:
  meta: ^1.1.5

dev_dependencies:
  mockito: ^3.0.0-beta+3
  test: ^1.3.0

environment:
  sdk: ">=1.19.0 <3.0.0"