name: display
description: Material metrics for an area of the screen.
version: 0.1.0
homepage: https://github.com/jifalops/display/display

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  meta: ^1.0.0

dev_dependencies:
  test:

