name: display
description: Material metrics for an area of the screen. Determine device type, column width, etc.
version: 0.2.1+1
homepage: https://github.com/jifalops/display/tree/master/display

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  meta: ^1.0.0

dev_dependencies:
  test:

